name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RSTIDAL_APP_TOKEN: ${{ secrets.RSTIDAL_APP_TOKEN }}
  RSTIDAL_USERNAME: ${{ secrets.RSTIDAL_USERNAME }}
  RSTIDAL_PASSWORD: ${{ secrets.RSTIDAL_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
